### ISSUE TITLE
npm install can't build sources

### ISSUE THREAD

**Issue by Vladislav-S** [luin/medis#119]
```bash
Building: /usr/local/bin/node /Users/Vlad/Downloads/medis-0.6.1/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/Vlad/Downloads/medis-0.6.1/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.13\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.2.1
gyp verb command install [ '8.2.1' ]
gyp verb install input version string "8.2.1"
gyp verb install installing version: 8.2.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.2.1
gyp verb build dir attempting to create "build" dir: /Users/Vlad/Downloads/medis-0.6.1/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /Users/Vlad/Downloads/medis-0.6.1/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/Vlad/Downloads/medis-0.6.1/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/Vlad/Downloads/medis-0.6.1/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/Vlad/Downloads/medis-0.6.1/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/Vlad/Downloads/medis-0.6.1/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Vlad/Downloads/medis-0.6.1/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Vlad/Downloads/medis-0.6.1/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Vlad/.node-gyp/8.2.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Vlad/.node-gyp/8.2.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/Vlad/Downloads/medis-0.6.1/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/Vlad/.node-gyp/8.2.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Vlad/Downloads/medis-0.6.1/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/Vlad/.node-gyp/8.2.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.3.6"' -I/Users/Vlad/.node-gyp/8.2.1/include/node -I/Users/Vlad/.node-gyp/8.2.1/src -I/Users/Vlad/.node-gyp/8.2.1/deps/uv/include -I/Users/Vlad/.node-gyp/8.2.1/deps/v8/include -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
c++: ошибка: unrecognized command line option «-stdlib=libc++»
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Vlad/Downloads/medis-0.6.1/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/Users/Vlad/Downloads/medis-0.6.1/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/Vlad/Downloads/medis-0.6.1/node_modules/node-sass
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN react-transition-group@2.2.1 requires a peer of react@>=15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@2.2.1 requires a peer of react-dom@>=15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@0.5.9 requires a peer of file-loader@* but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Vlad/.npm/_logs/2018-03-01T21_01_14_635Z-debug.log
```

**Comment by imiem** [comment]
I meet same error

**Comment by RamnathRepakula** [comment]
Got same problem on windows. Upgrading node-sass to latest version solved my problem.

**Comment by zhangyangzeyu** [comment]
what to do with this problem ??

**Comment by HubBoy** [comment]
$ npm install
$ npm run dev
$ npm start
Build Medis
$ npm run deploy
$ ./Medis.app

**Comment by ramsrib** [comment]
It uses old version of node-sass which doesn't exists in github releases anymore, so upgrading it will fix the problem.
```

> node-sass@3.13.1 install /Users/sriram/Downloads/medis-0.6.1/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-72_binding.node":

HTTP error 404 Not Found
```

**Comment by ramsrib** [comment]
I think it's already fixed in the master branch.

**Comment by zhangyangzeyu** [comment]
OK. I will try again. thanks



---Original---

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
