### ISSUE TITLE
Can't open Medis.app

### ISSUE THREAD

**Issue by wzlee** [luin/medis#127]
![image](https://user-images.githubusercontent.com/4182865/41082575-6532d65e-6a61-11e8-817b-e0313188ef6e.png)
```
Uncaught Exception:
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Object.<anonymous> (/Users/leo/git/github/medis/Medis.app/Contents/Resources/atom.asar/browser/lib/init.js:130:10)
    at Object.<anonymous> (/Users/leo/git/github/medis/Medis.app/Contents/Resources/atom.asar/browser/lib/init.js:132:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
```

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
