### ISSUE TITLE
Aftre donwload tar.gz for macos，excute 'npm install' throw exception

### ISSUE THREAD

**Issue by wzlee** [luin/medis#128]
![image](https://user-images.githubusercontent.com/4182865/41083384-ae4e6270-6a63-11e8-9a7f-82e401587f99.png)
```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/Users/leo/.Trash/medis-0.6.1/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/Users/leo/.Trash/medis-0.6.1/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/Users/leo/.Trash/medis-0.6.1/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/Users/leo/.Trash/medis-0.6.1/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/leo/.Trash/medis-0.6.1/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/leo/.Trash/medis-0.6.1/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/Users/leo/.Trash/medis-0.6.1/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/Users/leo/.Trash/medis-0.6.1/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/Users/leo/.Trash/medis-0.6.1/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/Users/leo/.Trash/medis-0.6.1/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/Users/leo/.Trash/medis-0.6.1/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/leo/.Trash/medis-0.6.1/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/Cellar/node/9.11.1/bin/node" "/Users/leo/.Trash/medis-0.6.1/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/leo/.Trash/medis-0.6.1/node_modules/node-sass
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN url-loader@0.5.9 requires a peer of file-loader@* but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@2.3.1 requires a peer of react@>=15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@2.3.1 requires a peer of react-dom@>=15.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leo/.npm/_logs/2018-06-07T06_57_25_689Z-debug.log
```

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
