### ISSUE TITLE
Unhandled rejection ReplyError: ERR unknown command 'config'

### ISSUE THREAD

**Issue by mneumark** [luin/medis#38]
I built a dev version of Medis so I could look in the console on the server I was having issues.

I then connected to the server where I able to connect successfully. The database was not showing up but the work around of using  `select #` works fine. But after about 15 to 20 seconds, I get a pop up that says "Redis Error: Connection failed" and then I'm booted out.

Which is bizarre because I am able to interact with the server otherwise.

I will say that unlike my localhost, this server cannot seem to get configurations, just an empty screen. Something connected to that is causing this issue it seems, but instead of just not letting me configure the server's config, it disconnects me.

Here are is the error from my logs:

```
Unhandled rejection ReplyError: ERR unknown command 'config'
    at Config.load (file:///Users/mneumark/Desktop/medis/main.js:75755:25)
    at new Config (file:///Users/mneumark/Desktop/medis/main.js:75747:11)
    at ReactCompositeComponentMixin.mountComponent (file:///Users/mneumark/Desktop/medis/main.js:7320:19)
    at wrapper [as mountComponent] (file:///Users/mneumark/Desktop/medis/main.js:1510:22)
    at Object.ReactReconciler.mountComponent (file:///Users/mneumark/Desktop/medis/main.js:5702:36)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (file:///Users/mneumark/Desktop/medis/main.js:14272:45)
    at ReactDOMComponent.Mixin._createContentMarkup (file:///Users/mneumark/Desktop/medis/main.js:11447:33)
    at ReactDOMComponent.Mixin.mountComponent (file:///Users/mneumark/Desktop/medis/main.js:11335:30)
    at Object.ReactReconciler.mountComponent (file:///Users/mneumark/Desktop/medis/main.js:5702:36)
    at ReactCompositeComponentMixin.mountComponent (file:///Users/mneumark/Desktop/medis/main.js:7397:35)
    at wrapper [as mountComponent] (file:///Users/mneumark/Desktop/medis/main.js:1510:22)
    at Object.ReactReconciler.mountComponent (file:///Users/mneumark/Desktop/medis/main.js:5702:36)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (file:///Users/mneumark/Desktop/medis/main.js:14272:45)
    at ReactDOMComponent.Mixin._createContentMarkup (file:///Users/mneumark/Desktop/medis/main.js:11447:33)
    at ReactDOMComponent.Mixin.mountComponent (file:///Users/mneumark/Desktop/medis/main.js:11335:30)
```

**Comment by mneumark** [comment]
Oh, Thought I'd note, here is the info for the server I'm connecting to thats giving me trouble:
```

redis> info
# Server
redis_version:3.0.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:7fbe38325a8bfa9
redis_mode:standalone
os:Darwin 15.6.0 x86_64
arch_bits:64
multiplexing_api:kqueue
gcc_version:4.2.1
process_id:803
run_id:a01040f783651b9b73adf2f22200f12d493474f0
tcp_port:6379
uptime_in_seconds:72518
uptime_in_days:0
hz:10
lru_clock:11941114
config_file:/usr/local/etc/redis.conf

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:1486160
used_memory_human:1.42M
used_memory_rss:1372160
used_memory_peak:1487184
used_memory_peak_human:1.42M
used_memory_lua:36864
mem_fragmentation_ratio:0.92
mem_allocator:libc

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1471486388
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:1
total_commands_processed:92
instantaneous_ops_per_sec:0
total_net_input_bytes:2856
total_net_output_bytes:89409
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:17
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:7.75
used_cpu_user:4.12
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=12,expires=0,avg_ttl=0
db5:keys=9,expires=0,avg_ttl=0
```

**Comment by luin** [comment]
Hello 👋 

Our development focus has now shifted to the next generation of Medis: [Medis 2](https://getmedis.com/). Compared to its predecessor, Medis 2 offers enhanced performance, more powerful features, and a more delightful interface. If you encounter any problems with Medis 2, feel free to reopen this issue, and together, we can explore possible solutions.

Download Medis 2 for free: https://getmedis.com/. Thanks for using and supporting Medis 1!
