### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by hsz1273327** [luin/medis#76]
似乎是electron的问题,但不知道怎么解决

```shell
/Users/huangsizhe/WORKSPACE/medis-mas/server/windowManager.js:10
    app.on('browser-window-blur', this.emit.bind(this, 'blur'));

TypeError: Cannot read property 'on' of undefined
    at new WindowManager (/Users/huangsizhe/WORKSPACE/medis-mas/server/windowManager.js:10:8)
    at Object.<anonymous> (/Users/huangsizhe/WORKSPACE/medis-mas/server/windowManager.js:66:18)
    at Object.<anonymous> (/Users/huangsizhe/WORKSPACE/medis-mas/server/windowManager.js:68:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

```

**Comment by luin** [comment]
试试 master 分支的新代码
