### ISSUE TITLE
Cannot run medis from mas branch

### ISSUE THREAD

**Issue by oneassasin** [luin/medis#77]
App threw an error during load
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/onea/Projects/nodejs/medis/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/onea/Projects/nodejs/medis/server/menu.js:3:13)
    at Object.<anonymous> (/Users/onea/Projects/nodejs/medis/server/menu.js:188:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

Mac, node v6.10.2

**Comment by domguinard** [comment]
Same error here, tried on 4 LTS and 7.0.0

**Comment by tcstory** [comment]
yeah, same error, tried on mac

**Comment by ogasawaraShinnosuke** [comment]
It was corrected in master.
