### ISSUE TITLE
npm run deploy报错

### ISSUE THREAD

**Issue by ikaren** [luin/medis#82]
> medis@0.6.1 deploy /Users/karen/softwares/medis-mas
> NODE_ENV=production ./bin/deploy

Hash: 00c61237cba943267c29
Version: webpack 1.15.0
Time: 36080ms
             Asset     Size  Chunks             Chunk Names
           main.js  1.27 MB       0  [emitted]  main
pattern-manager.js   300 kB       1  [emitted]  pattern-manager
    + 429 hidden modules
Downloading tmp-6279-1-SHASUMS256.txt-1.6.2
[============================================>] 100.0% of 2.85 kB (2.85 kB/s)
Packaging app for platform mas x64 using electron v1.6.2
flating... /Users/karen/softwares/medis-mas/out/Medis-mas-x64/Medis.app
Unhandled rejection Error: No identity found for signing.
    at /Users/karen/softwares/medis-mas/node_modules/electron-osx-sign/flat.js:108:35
    at tryCatcher (/Users/karen/softwares/medis-mas/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/karen/softwares/medis-mas/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/karen/softwares/medis-mas/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/karen/softwares/medis-mas/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/karen/softwares/medis-mas/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/karen/softwares/medis-mas/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/karen/softwares/medis-mas/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/karen/softwares/medis-mas/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

虽然报错了，但是生成的medis.app也能打开。这个有什么影响吗？

**Comment by luin** [comment]
这个是签名的逻辑，如果能打开的话就没有影响
